# Generated by Django 3.2.9 on 2022-05-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Username', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'Librarian-table',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Username', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=14)),
                ('LibrarianId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to='libraryapp.librarian')),
            ],
            options={
                'db_table': 'Member-table',
            },
        ),
    ]
